// <auto-generated />
using System;
using FiapCloudGames.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("VARCHAR(400)");

                    b.Property<string>("Genero")                        
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Jogo", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.JogosPromocoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("JogoId")
                        .HasColumnType("INT");

                    b.Property<int>("PromocaoId")
                        .HasColumnType("INT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("PromocaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("JogosPromocoes", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Level")
                        .HasColumnType("NVARCHAR(128)");

                    b.Property<string>("Message")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Promocao", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.UsuarioJogoPropriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<int>("JogoId")
                        .HasColumnType("INT");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("PromocaoId")
                        .HasColumnType("INT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("PromocaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioJogoPropriedade", (string)null);
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Jogo", b =>
                {
                    b.HasOne("FiapCloudGame.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Jogo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.JogosPromocoes", b =>
                {
                    b.HasOne("FiapCloudGame.Domain.Entities.Jogo", "Jogo")
                        .WithMany("JogosPromocoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGame.Domain.Entities.Promocao", "Promocao")
                        .WithMany("JogosPromocoes")
                        .HasForeignKey("PromocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGame.Domain.Entities.Usuario", "Usuario")
                        .WithMany("JogosPromocoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Promocao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Promocao", b =>
                {
                    b.HasOne("FiapCloudGame.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Promocao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.UsuarioJogoPropriedade", b =>
                {
                    b.HasOne("FiapCloudGame.Domain.Entities.Jogo", "Jogo")
                        .WithMany("UsuarioJogoPropriedades")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGame.Domain.Entities.Promocao", "Promocao")
                        .WithMany("UsuarioJogoPropriedades")
                        .HasForeignKey("PromocaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiapCloudGame.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioJogoPropriedades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Promocao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Jogo", b =>
                {
                    b.Navigation("JogosPromocoes");

                    b.Navigation("UsuarioJogoPropriedades");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Promocao", b =>
                {
                    b.Navigation("JogosPromocoes");

                    b.Navigation("UsuarioJogoPropriedades");
                });

            modelBuilder.Entity("FiapCloudGame.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jogo");

                    b.Navigation("JogosPromocoes");

                    b.Navigation("Promocao");

                    b.Navigation("UsuarioJogoPropriedades");
                });
        }
    }
}
